/**
 * Machine-readable error codes returned in `error.code`. Clients branch on these,
 * never on `message`, so messages can be reworded freely.
 */
export const ErrorCode = {
  BAD_REQUEST: "BAD_REQUEST",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
  ACCOUNT_DISABLED: "ACCOUNT_DISABLED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  EMAIL_ALREADY_REGISTERED: "EMAIL_ALREADY_REGISTERED",
  PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
  UNPROCESSABLE_ENTITY: "UNPROCESSABLE_ENTITY",
  MEDIA_TOO_LARGE: "MEDIA_TOO_LARGE",
  MEDIA_UPLOAD_MISSING: "MEDIA_UPLOAD_MISSING",
  MEDIA_UPLOAD_INVALID: "MEDIA_UPLOAD_INVALID",
  MEDIA_NOT_USABLE: "MEDIA_NOT_USABLE",
  MEDIA_IN_USE: "MEDIA_IN_USE",
  SLUG_TAKEN: "SLUG_TAKEN",
  SKU_TAKEN: "SKU_TAKEN",
  RESOURCE_IN_USE: "RESOURCE_IN_USE",
  INVALID_COMPATIBILITY: "INVALID_COMPATIBILITY",
  INVALID_REFERENCE: "INVALID_REFERENCE",
  PRODUCT_UNAVAILABLE: "PRODUCT_UNAVAILABLE",
  INVALID_QUANTITY: "INVALID_QUANTITY",
  LIMIT_REACHED: "LIMIT_REACHED",
  RIDE_FULL: "RIDE_FULL",
  RIDE_CLOSED: "RIDE_CLOSED",
  ALREADY_REGISTERED: "ALREADY_REGISTERED",
  PAYMENT_NOT_CONFIGURED: "PAYMENT_NOT_CONFIGURED",
  LOCATION_NOT_FOUND: "LOCATION_NOT_FOUND",
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
  ROUTE_UNAVAILABLE: "ROUTE_UNAVAILABLE",
  JOURNEY_TOO_LONG: "JOURNEY_TOO_LONG",
  PLANNING_UNAVAILABLE: "PLANNING_UNAVAILABLE",
  PLAN_NOT_VERIFIED: "PLAN_NOT_VERIFIED",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  STORAGE_NOT_CONFIGURED: "STORAGE_NOT_CONFIGURED",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

const DEFAULT_CODES: Record<number, ErrorCode> = {
  400: ErrorCode.BAD_REQUEST,
  401: ErrorCode.UNAUTHORIZED,
  403: ErrorCode.FORBIDDEN,
  404: ErrorCode.NOT_FOUND,
  409: ErrorCode.CONFLICT,
  413: ErrorCode.PAYLOAD_TOO_LARGE,
  422: ErrorCode.UNPROCESSABLE_ENTITY,
  429: ErrorCode.TOO_MANY_REQUESTS,
  503: ErrorCode.SERVICE_UNAVAILABLE,
};

export function defaultErrorCode(status: number): ErrorCode {
  return (
    DEFAULT_CODES[status] ?? (status >= 500 ? ErrorCode.INTERNAL_ERROR : ErrorCode.BAD_REQUEST)
  );
}
