/**
 * What the journey planner needs from a language model: one JSON answer to one
 * prompt. Gemini and Ollama implement it; the planner's own logic (facts,
 * validation, the plan) lives above this and is the same for both.
 */

/** A JSON Schema subset both providers accept for structured output. */
export type JsonSchema = {
  type: "object" | "array" | "string" | "integer" | "number" | "boolean";
  description?: string;
  properties?: Record<string, JsonSchema>;
  required?: string[];
  items?: JsonSchema;
  enum?: string[];
  nullable?: boolean;
};

export type AiRequest = {
  /** Rules the model must follow. */
  system: string;
  /** The task and the verified data. */
  user: string;
  /** Shape the answer must take. */
  schema: JsonSchema;
};

export type AiResponse = {
  /** The model's answer: JSON as text. Not yet validated. */
  text: string;
  /** The model that actually answered, for the plan's "generated by" line. */
  model: string;
};

export interface AiProvider {
  /** "gemini" or "ollama". */
  readonly name: string;
  /** Shown to riders, e.g. "Gemini". */
  readonly label: string;
  /** False when it has no credentials: it is then skipped, not attempted. */
  readonly configured: boolean;
  generate(request: AiRequest): Promise<AiResponse>;
}

/** A provider could not produce an answer. `detail` is for logs only, never for clients. */
export class AiProviderError extends Error {
  constructor(
    readonly provider: string,
    readonly detail: string,
  ) {
    super(`${provider}: ${detail}`);
    this.name = "AiProviderError";
  }
}
