/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as GarageRouteImport } from './routes/garage'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LoginRouteImport } from './routes/login'
import { Route as My36SpokesRouteImport } from './routes/my-36-spokes'
import { Route as RidesRouteImport } from './routes/rides'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as TravelRouteImport } from './routes/travel'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const GarageRoute = GarageRouteImport.update({
  id: '/garage',
  path: '/garage',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const My36SpokesRoute = My36SpokesRouteImport.update({
  id: '/my-36-spokes',
  path: '/my-36-spokes',
  getParentRoute: () => rootRouteImport,
} as any)
const RidesRoute = RidesRouteImport.update({
  id: '/rides',
  path: '/rides',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelRoute = TravelRouteImport.update({
  id: '/travel',
  path: '/travel',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/garage': typeof GarageRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/my-36-spokes': typeof My36SpokesRoute
  '/rides': typeof RidesRoute
  '/shop': typeof ShopRoute
  '/stories': typeof StoriesRoute
  '/travel': typeof TravelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/garage': typeof GarageRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/my-36-spokes': typeof My36SpokesRoute
  '/rides': typeof RidesRoute
  '/shop': typeof ShopRoute
  '/stories': typeof StoriesRoute
  '/travel': typeof TravelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/garage': typeof GarageRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/my-36-spokes': typeof My36SpokesRoute
  '/rides': typeof RidesRoute
  '/shop': typeof ShopRoute
  '/stories': typeof StoriesRoute
  '/travel': typeof TravelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community'
    | '/garage'
    | '/join'
    | '/login'
    | '/my-36-spokes'
    | '/rides'
    | '/shop'
    | '/stories'
    | '/travel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/garage'
    | '/join'
    | '/login'
    | '/my-36-spokes'
    | '/rides'
    | '/shop'
    | '/stories'
    | '/travel'
  id:
    | '__root__'
    | '/'
    | '/community'
    | '/garage'
    | '/join'
    | '/login'
    | '/my-36-spokes'
    | '/rides'
    | '/shop'
    | '/stories'
    | '/travel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityRoute: typeof CommunityRoute
  GarageRoute: typeof GarageRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  My36SpokesRoute: typeof My36SpokesRoute
  RidesRoute: typeof RidesRoute
  ShopRoute: typeof ShopRoute
  StoriesRoute: typeof StoriesRoute
  TravelRoute: typeof TravelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garage': {
      id: '/garage'
      path: '/garage'
      fullPath: '/garage'
      preLoaderRoute: typeof GarageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-36-spokes': {
      id: '/my-36-spokes'
      path: '/my-36-spokes'
      fullPath: '/my-36-spokes'
      preLoaderRoute: typeof My36SpokesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rides': {
      id: '/rides'
      path: '/rides'
      fullPath: '/rides'
      preLoaderRoute: typeof RidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel': {
      id: '/travel'
      path: '/travel'
      fullPath: '/travel'
      preLoaderRoute: typeof TravelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityRoute: CommunityRoute,
  GarageRoute: GarageRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  My36SpokesRoute: My36SpokesRoute,
  RidesRoute: RidesRoute,
  ShopRoute: ShopRoute,
  StoriesRoute: StoriesRoute,
  TravelRoute: TravelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
