/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LoginRouteImport } from './routes/login'
import { Route as My36SpokesRouteRouteImport } from './routes/my-36-spokes/route'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ShopRouteRouteImport } from './routes/shop/route'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminBikesRouteImport } from './routes/admin/bikes'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminHeroRouteImport } from './routes/admin/hero'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminPathsRouteImport } from './routes/admin/paths'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminSocialRouteImport } from './routes/admin/social'
import { Route as CommunityIndexRouteImport } from './routes/community/index'
import { Route as CommunityGroupsRouteImport } from './routes/community/groups'
import { Route as CommunityRidersRouteImport } from './routes/community/riders'
import { Route as GarageIndexRouteImport } from './routes/garage/index'
import { Route as GarageBikeRouteImport } from './routes/garage/$bike'
import { Route as My36SpokesIndexRouteImport } from './routes/my-36-spokes/index'
import { Route as My36SpokesCommunityRouteImport } from './routes/my-36-spokes/community'
import { Route as My36SpokesGarageRouteImport } from './routes/my-36-spokes/garage'
import { Route as My36SpokesRidesRouteImport } from './routes/my-36-spokes/rides'
import { Route as My36SpokesShopRouteImport } from './routes/my-36-spokes/shop'
import { Route as My36SpokesTravelRouteImport } from './routes/my-36-spokes/travel'
import { Route as PlanIndexRouteImport } from './routes/plan/index'
import { Route as ProductSlugRouteImport } from './routes/product/$slug'
import { Route as RidesIndexRouteImport } from './routes/rides/index'
import { Route as RidesSlugRouteImport } from './routes/rides/$slug'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as ShopCategoryRouteImport } from './routes/shop/$category'
import { Route as StoriesIndexRouteImport } from './routes/stories/index'
import { Route as StoriesSlugRouteImport } from './routes/stories/$slug'
import { Route as TravelIndexRouteImport } from './routes/travel/index'
import { Route as TravelDestinationRouteImport } from './routes/travel/$destination'
import { Route as TravelDestinationsRouteImport } from './routes/travel/destinations'
import { Route as AdminCommunityIndexRouteImport } from './routes/admin/community/index'
import { Route as AdminCommunityFoundersRouteImport } from './routes/admin/community/founders'
import { Route as AdminCommunityGroupsRouteImport } from './routes/admin/community/groups'
import { Route as AdminCommunityRidersRouteImport } from './routes/admin/community/riders'
import { Route as AdminCommunityStoriesRouteImport } from './routes/admin/community/stories'
import { Route as AdminDestinationsIndexRouteImport } from './routes/admin/destinations/index'
import { Route as AdminDestinationsDestinationIdRouteImport } from './routes/admin/destinations/$destinationId'
import { Route as AdminDestinationsNewRouteImport } from './routes/admin/destinations/new'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminProductsProductIdRouteImport } from './routes/admin/products/$productId'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products/new'
import { Route as AdminRidesIndexRouteImport } from './routes/admin/rides/index'
import { Route as AdminRidesRideIdRouteImport } from './routes/admin/rides/$rideId'
import { Route as AdminRidesNewRouteImport } from './routes/admin/rides/new'
import { Route as AdminTripsIndexRouteImport } from './routes/admin/trips/index'
import { Route as AdminTripsTripIdRouteImport } from './routes/admin/trips/$tripId'
import { Route as AdminTripsNewRouteImport } from './routes/admin/trips/new'
import { Route as CommunityGroupsIndexRouteImport } from './routes/community/groups/index'
import { Route as CommunityGroupsSlugRouteImport } from './routes/community/groups/$slug'
import { Route as My36SpokesJourneysIndexRouteImport } from './routes/my-36-spokes/journeys.index'
import { Route as My36SpokesJourneysJourneyIdRouteImport } from './routes/my-36-spokes/journeys.$journeyId'
import { Route as RidesSlugBookRouteImport } from './routes/rides/$slug_.book'
import { Route as TravelTripsIndexRouteImport } from './routes/travel/trips/index'
import { Route as TravelTripsSlugRouteImport } from './routes/travel/trips/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const My36SpokesRouteRoute = My36SpokesRouteRouteImport.update({
  id: '/my-36-spokes',
  path: '/my-36-spokes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRouteRoute = ShopRouteRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBikesRoute = AdminBikesRouteImport.update({
  id: '/bikes',
  path: '/bikes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHeroRoute = AdminHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPathsRoute = AdminPathsRouteImport.update({
  id: '/paths',
  path: '/paths',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSocialRoute = AdminSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityGroupsRoute = CommunityGroupsRouteImport.update({
  id: '/community/groups',
  path: '/community/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRidersRoute = CommunityRidersRouteImport.update({
  id: '/community/riders',
  path: '/community/riders',
  getParentRoute: () => rootRouteImport,
} as any)
const GarageIndexRoute = GarageIndexRouteImport.update({
  id: '/garage/',
  path: '/garage/',
  getParentRoute: () => rootRouteImport,
} as any)
const GarageBikeRoute = GarageBikeRouteImport.update({
  id: '/garage/$bike',
  path: '/garage/$bike',
  getParentRoute: () => rootRouteImport,
} as any)
const My36SpokesIndexRoute = My36SpokesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => My36SpokesRouteRoute,
} as any)
const My36SpokesCommunityRoute = My36SpokesCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => My36SpokesRouteRoute,
} as any)
const My36SpokesGarageRoute = My36SpokesGarageRouteImport.update({
  id: '/garage',
  path: '/garage',
  getParentRoute: () => My36SpokesRouteRoute,
} as any)
const My36SpokesRidesRoute = My36SpokesRidesRouteImport.update({
  id: '/rides',
  path: '/rides',
  getParentRoute: () => My36SpokesRouteRoute,
} as any)
const My36SpokesShopRoute = My36SpokesShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => My36SpokesRouteRoute,
} as any)
const My36SpokesTravelRoute = My36SpokesTravelRouteImport.update({
  id: '/travel',
  path: '/travel',
  getParentRoute: () => My36SpokesRouteRoute,
} as any)
const PlanIndexRoute = PlanIndexRouteImport.update({
  id: '/plan/',
  path: '/plan/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RidesIndexRoute = RidesIndexRouteImport.update({
  id: '/rides/',
  path: '/rides/',
  getParentRoute: () => rootRouteImport,
} as any)
const RidesSlugRoute = RidesSlugRouteImport.update({
  id: '/rides/$slug',
  path: '/rides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRouteRoute,
} as any)
const ShopCategoryRoute = ShopCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => ShopRouteRoute,
} as any)
const StoriesIndexRoute = StoriesIndexRouteImport.update({
  id: '/stories/',
  path: '/stories/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesSlugRoute = StoriesSlugRouteImport.update({
  id: '/stories/$slug',
  path: '/stories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelIndexRoute = TravelIndexRouteImport.update({
  id: '/travel/',
  path: '/travel/',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelDestinationRoute = TravelDestinationRouteImport.update({
  id: '/travel/$destination',
  path: '/travel/$destination',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelDestinationsRoute = TravelDestinationsRouteImport.update({
  id: '/travel/destinations',
  path: '/travel/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCommunityIndexRoute = AdminCommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCommunityFoundersRoute = AdminCommunityFoundersRouteImport.update({
  id: '/community/founders',
  path: '/community/founders',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCommunityGroupsRoute = AdminCommunityGroupsRouteImport.update({
  id: '/community/groups',
  path: '/community/groups',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCommunityRidersRoute = AdminCommunityRidersRouteImport.update({
  id: '/community/riders',
  path: '/community/riders',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCommunityStoriesRoute = AdminCommunityStoriesRouteImport.update({
  id: '/community/stories',
  path: '/community/stories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDestinationsIndexRoute = AdminDestinationsIndexRouteImport.update({
  id: '/destinations/',
  path: '/destinations/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDestinationsDestinationIdRoute =
  AdminDestinationsDestinationIdRouteImport.update({
    id: '/destinations/$destinationId',
    path: '/destinations/$destinationId',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminDestinationsNewRoute = AdminDestinationsNewRouteImport.update({
  id: '/destinations/new',
  path: '/destinations/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsProductIdRoute = AdminProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRidesIndexRoute = AdminRidesIndexRouteImport.update({
  id: '/rides/',
  path: '/rides/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRidesRideIdRoute = AdminRidesRideIdRouteImport.update({
  id: '/rides/$rideId',
  path: '/rides/$rideId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRidesNewRoute = AdminRidesNewRouteImport.update({
  id: '/rides/new',
  path: '/rides/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTripsIndexRoute = AdminTripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTripsTripIdRoute = AdminTripsTripIdRouteImport.update({
  id: '/trips/$tripId',
  path: '/trips/$tripId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTripsNewRoute = AdminTripsNewRouteImport.update({
  id: '/trips/new',
  path: '/trips/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CommunityGroupsIndexRoute = CommunityGroupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommunityGroupsRoute,
} as any)
const CommunityGroupsSlugRoute = CommunityGroupsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CommunityGroupsRoute,
} as any)
const My36SpokesJourneysIndexRoute = My36SpokesJourneysIndexRouteImport.update({
  id: '/journeys/',
  path: '/journeys/',
  getParentRoute: () => My36SpokesRouteRoute,
} as any)
const My36SpokesJourneysJourneyIdRoute =
  My36SpokesJourneysJourneyIdRouteImport.update({
    id: '/journeys/$journeyId',
    path: '/journeys/$journeyId',
    getParentRoute: () => My36SpokesRouteRoute,
  } as any)
const RidesSlugBookRoute = RidesSlugBookRouteImport.update({
  id: '/rides/$slug_/book',
  path: '/rides/$slug/book',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelTripsIndexRoute = TravelTripsIndexRouteImport.update({
  id: '/travel/trips/',
  path: '/travel/trips/',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelTripsSlugRoute = TravelTripsSlugRouteImport.update({
  id: '/travel/trips/$slug',
  path: '/travel/trips/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/my-36-spokes': typeof My36SpokesRouteRouteWithChildren
  '/shop': typeof ShopRouteRouteWithChildren
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/admin/bikes': typeof AdminBikesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/paths': typeof AdminPathsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/social': typeof AdminSocialRoute
  '/community/groups': typeof CommunityGroupsRouteWithChildren
  '/community/riders': typeof CommunityRidersRoute
  '/garage/$bike': typeof GarageBikeRoute
  '/my-36-spokes/community': typeof My36SpokesCommunityRoute
  '/my-36-spokes/garage': typeof My36SpokesGarageRoute
  '/my-36-spokes/rides': typeof My36SpokesRidesRoute
  '/my-36-spokes/shop': typeof My36SpokesShopRoute
  '/my-36-spokes/travel': typeof My36SpokesTravelRoute
  '/product/$slug': typeof ProductSlugRoute
  '/rides/$slug': typeof RidesSlugRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/travel/$destination': typeof TravelDestinationRoute
  '/travel/destinations': typeof TravelDestinationsRoute
  '/about/': typeof AboutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/garage/': typeof GarageIndexRoute
  '/my-36-spokes/': typeof My36SpokesIndexRoute
  '/plan/': typeof PlanIndexRoute
  '/rides/': typeof RidesIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/stories/': typeof StoriesIndexRoute
  '/travel/': typeof TravelIndexRoute
  '/admin/community/founders': typeof AdminCommunityFoundersRoute
  '/admin/community/groups': typeof AdminCommunityGroupsRoute
  '/admin/community/riders': typeof AdminCommunityRidersRoute
  '/admin/community/stories': typeof AdminCommunityStoriesRoute
  '/admin/destinations/$destinationId': typeof AdminDestinationsDestinationIdRoute
  '/admin/destinations/new': typeof AdminDestinationsNewRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/rides/$rideId': typeof AdminRidesRideIdRoute
  '/admin/rides/new': typeof AdminRidesNewRoute
  '/admin/trips/$tripId': typeof AdminTripsTripIdRoute
  '/admin/trips/new': typeof AdminTripsNewRoute
  '/community/groups/$slug': typeof CommunityGroupsSlugRoute
  '/my-36-spokes/journeys/$journeyId': typeof My36SpokesJourneysJourneyIdRoute
  '/rides/$slug/book': typeof RidesSlugBookRoute
  '/travel/trips/$slug': typeof TravelTripsSlugRoute
  '/admin/community/': typeof AdminCommunityIndexRoute
  '/admin/destinations/': typeof AdminDestinationsIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/rides/': typeof AdminRidesIndexRoute
  '/admin/trips/': typeof AdminTripsIndexRoute
  '/community/groups/': typeof CommunityGroupsIndexRoute
  '/my-36-spokes/journeys/': typeof My36SpokesJourneysIndexRoute
  '/travel/trips/': typeof TravelTripsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/admin/bikes': typeof AdminBikesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/paths': typeof AdminPathsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/social': typeof AdminSocialRoute
  '/community/riders': typeof CommunityRidersRoute
  '/garage/$bike': typeof GarageBikeRoute
  '/my-36-spokes/community': typeof My36SpokesCommunityRoute
  '/my-36-spokes/garage': typeof My36SpokesGarageRoute
  '/my-36-spokes/rides': typeof My36SpokesRidesRoute
  '/my-36-spokes/shop': typeof My36SpokesShopRoute
  '/my-36-spokes/travel': typeof My36SpokesTravelRoute
  '/product/$slug': typeof ProductSlugRoute
  '/rides/$slug': typeof RidesSlugRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/travel/$destination': typeof TravelDestinationRoute
  '/travel/destinations': typeof TravelDestinationsRoute
  '/about': typeof AboutIndexRoute
  '/admin': typeof AdminIndexRoute
  '/community': typeof CommunityIndexRoute
  '/garage': typeof GarageIndexRoute
  '/my-36-spokes': typeof My36SpokesIndexRoute
  '/plan': typeof PlanIndexRoute
  '/rides': typeof RidesIndexRoute
  '/shop': typeof ShopIndexRoute
  '/stories': typeof StoriesIndexRoute
  '/travel': typeof TravelIndexRoute
  '/admin/community/founders': typeof AdminCommunityFoundersRoute
  '/admin/community/groups': typeof AdminCommunityGroupsRoute
  '/admin/community/riders': typeof AdminCommunityRidersRoute
  '/admin/community/stories': typeof AdminCommunityStoriesRoute
  '/admin/destinations/$destinationId': typeof AdminDestinationsDestinationIdRoute
  '/admin/destinations/new': typeof AdminDestinationsNewRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/rides/$rideId': typeof AdminRidesRideIdRoute
  '/admin/rides/new': typeof AdminRidesNewRoute
  '/admin/trips/$tripId': typeof AdminTripsTripIdRoute
  '/admin/trips/new': typeof AdminTripsNewRoute
  '/community/groups/$slug': typeof CommunityGroupsSlugRoute
  '/my-36-spokes/journeys/$journeyId': typeof My36SpokesJourneysJourneyIdRoute
  '/rides/$slug/book': typeof RidesSlugBookRoute
  '/travel/trips/$slug': typeof TravelTripsSlugRoute
  '/admin/community': typeof AdminCommunityIndexRoute
  '/admin/destinations': typeof AdminDestinationsIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/rides': typeof AdminRidesIndexRoute
  '/admin/trips': typeof AdminTripsIndexRoute
  '/community/groups': typeof CommunityGroupsIndexRoute
  '/my-36-spokes/journeys': typeof My36SpokesJourneysIndexRoute
  '/travel/trips': typeof TravelTripsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/my-36-spokes': typeof My36SpokesRouteRouteWithChildren
  '/shop': typeof ShopRouteRouteWithChildren
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/admin/bikes': typeof AdminBikesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/paths': typeof AdminPathsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/social': typeof AdminSocialRoute
  '/community/groups': typeof CommunityGroupsRouteWithChildren
  '/community/riders': typeof CommunityRidersRoute
  '/garage/$bike': typeof GarageBikeRoute
  '/my-36-spokes/community': typeof My36SpokesCommunityRoute
  '/my-36-spokes/garage': typeof My36SpokesGarageRoute
  '/my-36-spokes/rides': typeof My36SpokesRidesRoute
  '/my-36-spokes/shop': typeof My36SpokesShopRoute
  '/my-36-spokes/travel': typeof My36SpokesTravelRoute
  '/product/$slug': typeof ProductSlugRoute
  '/rides/$slug': typeof RidesSlugRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/travel/$destination': typeof TravelDestinationRoute
  '/travel/destinations': typeof TravelDestinationsRoute
  '/about/': typeof AboutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/garage/': typeof GarageIndexRoute
  '/my-36-spokes/': typeof My36SpokesIndexRoute
  '/plan/': typeof PlanIndexRoute
  '/rides/': typeof RidesIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/stories/': typeof StoriesIndexRoute
  '/travel/': typeof TravelIndexRoute
  '/admin/community/founders': typeof AdminCommunityFoundersRoute
  '/admin/community/groups': typeof AdminCommunityGroupsRoute
  '/admin/community/riders': typeof AdminCommunityRidersRoute
  '/admin/community/stories': typeof AdminCommunityStoriesRoute
  '/admin/destinations/$destinationId': typeof AdminDestinationsDestinationIdRoute
  '/admin/destinations/new': typeof AdminDestinationsNewRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/rides/$rideId': typeof AdminRidesRideIdRoute
  '/admin/rides/new': typeof AdminRidesNewRoute
  '/admin/trips/$tripId': typeof AdminTripsTripIdRoute
  '/admin/trips/new': typeof AdminTripsNewRoute
  '/community/groups/$slug': typeof CommunityGroupsSlugRoute
  '/my-36-spokes/journeys/$journeyId': typeof My36SpokesJourneysJourneyIdRoute
  '/rides/$slug_/book': typeof RidesSlugBookRoute
  '/travel/trips/$slug': typeof TravelTripsSlugRoute
  '/admin/community/': typeof AdminCommunityIndexRoute
  '/admin/destinations/': typeof AdminDestinationsIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/rides/': typeof AdminRidesIndexRoute
  '/admin/trips/': typeof AdminTripsIndexRoute
  '/community/groups/': typeof CommunityGroupsIndexRoute
  '/my-36-spokes/journeys/': typeof My36SpokesJourneysIndexRoute
  '/travel/trips/': typeof TravelTripsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/my-36-spokes'
    | '/shop'
    | '/join'
    | '/login'
    | '/profile'
    | '/admin/bikes'
    | '/admin/categories'
    | '/admin/hero'
    | '/admin/media'
    | '/admin/paths'
    | '/admin/payments'
    | '/admin/social'
    | '/community/groups'
    | '/community/riders'
    | '/garage/$bike'
    | '/my-36-spokes/community'
    | '/my-36-spokes/garage'
    | '/my-36-spokes/rides'
    | '/my-36-spokes/shop'
    | '/my-36-spokes/travel'
    | '/product/$slug'
    | '/rides/$slug'
    | '/shop/$category'
    | '/stories/$slug'
    | '/travel/$destination'
    | '/travel/destinations'
    | '/about/'
    | '/admin/'
    | '/community/'
    | '/garage/'
    | '/my-36-spokes/'
    | '/plan/'
    | '/rides/'
    | '/shop/'
    | '/stories/'
    | '/travel/'
    | '/admin/community/founders'
    | '/admin/community/groups'
    | '/admin/community/riders'
    | '/admin/community/stories'
    | '/admin/destinations/$destinationId'
    | '/admin/destinations/new'
    | '/admin/products/$productId'
    | '/admin/products/new'
    | '/admin/rides/$rideId'
    | '/admin/rides/new'
    | '/admin/trips/$tripId'
    | '/admin/trips/new'
    | '/community/groups/$slug'
    | '/my-36-spokes/journeys/$journeyId'
    | '/rides/$slug/book'
    | '/travel/trips/$slug'
    | '/admin/community/'
    | '/admin/destinations/'
    | '/admin/products/'
    | '/admin/rides/'
    | '/admin/trips/'
    | '/community/groups/'
    | '/my-36-spokes/journeys/'
    | '/travel/trips/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/join'
    | '/login'
    | '/profile'
    | '/admin/bikes'
    | '/admin/categories'
    | '/admin/hero'
    | '/admin/media'
    | '/admin/paths'
    | '/admin/payments'
    | '/admin/social'
    | '/community/riders'
    | '/garage/$bike'
    | '/my-36-spokes/community'
    | '/my-36-spokes/garage'
    | '/my-36-spokes/rides'
    | '/my-36-spokes/shop'
    | '/my-36-spokes/travel'
    | '/product/$slug'
    | '/rides/$slug'
    | '/shop/$category'
    | '/stories/$slug'
    | '/travel/$destination'
    | '/travel/destinations'
    | '/about'
    | '/admin'
    | '/community'
    | '/garage'
    | '/my-36-spokes'
    | '/plan'
    | '/rides'
    | '/shop'
    | '/stories'
    | '/travel'
    | '/admin/community/founders'
    | '/admin/community/groups'
    | '/admin/community/riders'
    | '/admin/community/stories'
    | '/admin/destinations/$destinationId'
    | '/admin/destinations/new'
    | '/admin/products/$productId'
    | '/admin/products/new'
    | '/admin/rides/$rideId'
    | '/admin/rides/new'
    | '/admin/trips/$tripId'
    | '/admin/trips/new'
    | '/community/groups/$slug'
    | '/my-36-spokes/journeys/$journeyId'
    | '/rides/$slug/book'
    | '/travel/trips/$slug'
    | '/admin/community'
    | '/admin/destinations'
    | '/admin/products'
    | '/admin/rides'
    | '/admin/trips'
    | '/community/groups'
    | '/my-36-spokes/journeys'
    | '/travel/trips'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/my-36-spokes'
    | '/shop'
    | '/join'
    | '/login'
    | '/profile'
    | '/admin/bikes'
    | '/admin/categories'
    | '/admin/hero'
    | '/admin/media'
    | '/admin/paths'
    | '/admin/payments'
    | '/admin/social'
    | '/community/groups'
    | '/community/riders'
    | '/garage/$bike'
    | '/my-36-spokes/community'
    | '/my-36-spokes/garage'
    | '/my-36-spokes/rides'
    | '/my-36-spokes/shop'
    | '/my-36-spokes/travel'
    | '/product/$slug'
    | '/rides/$slug'
    | '/shop/$category'
    | '/stories/$slug'
    | '/travel/$destination'
    | '/travel/destinations'
    | '/about/'
    | '/admin/'
    | '/community/'
    | '/garage/'
    | '/my-36-spokes/'
    | '/plan/'
    | '/rides/'
    | '/shop/'
    | '/stories/'
    | '/travel/'
    | '/admin/community/founders'
    | '/admin/community/groups'
    | '/admin/community/riders'
    | '/admin/community/stories'
    | '/admin/destinations/$destinationId'
    | '/admin/destinations/new'
    | '/admin/products/$productId'
    | '/admin/products/new'
    | '/admin/rides/$rideId'
    | '/admin/rides/new'
    | '/admin/trips/$tripId'
    | '/admin/trips/new'
    | '/community/groups/$slug'
    | '/my-36-spokes/journeys/$journeyId'
    | '/rides/$slug_/book'
    | '/travel/trips/$slug'
    | '/admin/community/'
    | '/admin/destinations/'
    | '/admin/products/'
    | '/admin/rides/'
    | '/admin/trips/'
    | '/community/groups/'
    | '/my-36-spokes/journeys/'
    | '/travel/trips/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  My36SpokesRouteRoute: typeof My36SpokesRouteRouteWithChildren
  ShopRouteRoute: typeof ShopRouteRouteWithChildren
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  CommunityGroupsRoute: typeof CommunityGroupsRouteWithChildren
  CommunityRidersRoute: typeof CommunityRidersRoute
  GarageBikeRoute: typeof GarageBikeRoute
  ProductSlugRoute: typeof ProductSlugRoute
  RidesSlugRoute: typeof RidesSlugRoute
  StoriesSlugRoute: typeof StoriesSlugRoute
  TravelDestinationRoute: typeof TravelDestinationRoute
  TravelDestinationsRoute: typeof TravelDestinationsRoute
  AboutIndexRoute: typeof AboutIndexRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
  GarageIndexRoute: typeof GarageIndexRoute
  PlanIndexRoute: typeof PlanIndexRoute
  RidesIndexRoute: typeof RidesIndexRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
  TravelIndexRoute: typeof TravelIndexRoute
  RidesSlugBookRoute: typeof RidesSlugBookRoute
  TravelTripsSlugRoute: typeof TravelTripsSlugRoute
  TravelTripsIndexRoute: typeof TravelTripsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-36-spokes': {
      id: '/my-36-spokes'
      path: '/my-36-spokes'
      fullPath: '/my-36-spokes'
      preLoaderRoute: typeof My36SpokesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/bikes': {
      id: '/admin/bikes'
      path: '/bikes'
      fullPath: '/admin/bikes'
      preLoaderRoute: typeof AdminBikesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/hero': {
      id: '/admin/hero'
      path: '/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AdminHeroRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/paths': {
      id: '/admin/paths'
      path: '/paths'
      fullPath: '/admin/paths'
      preLoaderRoute: typeof AdminPathsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/social': {
      id: '/admin/social'
      path: '/social'
      fullPath: '/admin/social'
      preLoaderRoute: typeof AdminSocialRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/community/': {
      id: '/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/groups': {
      id: '/community/groups'
      path: '/community/groups'
      fullPath: '/community/groups'
      preLoaderRoute: typeof CommunityGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/riders': {
      id: '/community/riders'
      path: '/community/riders'
      fullPath: '/community/riders'
      preLoaderRoute: typeof CommunityRidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garage/': {
      id: '/garage/'
      path: '/garage'
      fullPath: '/garage/'
      preLoaderRoute: typeof GarageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garage/$bike': {
      id: '/garage/$bike'
      path: '/garage/$bike'
      fullPath: '/garage/$bike'
      preLoaderRoute: typeof GarageBikeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-36-spokes/': {
      id: '/my-36-spokes/'
      path: '/'
      fullPath: '/my-36-spokes/'
      preLoaderRoute: typeof My36SpokesIndexRouteImport
      parentRoute: typeof My36SpokesRouteRoute
    }
    '/my-36-spokes/community': {
      id: '/my-36-spokes/community'
      path: '/community'
      fullPath: '/my-36-spokes/community'
      preLoaderRoute: typeof My36SpokesCommunityRouteImport
      parentRoute: typeof My36SpokesRouteRoute
    }
    '/my-36-spokes/garage': {
      id: '/my-36-spokes/garage'
      path: '/garage'
      fullPath: '/my-36-spokes/garage'
      preLoaderRoute: typeof My36SpokesGarageRouteImport
      parentRoute: typeof My36SpokesRouteRoute
    }
    '/my-36-spokes/rides': {
      id: '/my-36-spokes/rides'
      path: '/rides'
      fullPath: '/my-36-spokes/rides'
      preLoaderRoute: typeof My36SpokesRidesRouteImport
      parentRoute: typeof My36SpokesRouteRoute
    }
    '/my-36-spokes/shop': {
      id: '/my-36-spokes/shop'
      path: '/shop'
      fullPath: '/my-36-spokes/shop'
      preLoaderRoute: typeof My36SpokesShopRouteImport
      parentRoute: typeof My36SpokesRouteRoute
    }
    '/my-36-spokes/travel': {
      id: '/my-36-spokes/travel'
      path: '/travel'
      fullPath: '/my-36-spokes/travel'
      preLoaderRoute: typeof My36SpokesTravelRouteImport
      parentRoute: typeof My36SpokesRouteRoute
    }
    '/plan/': {
      id: '/plan/'
      path: '/plan'
      fullPath: '/plan/'
      preLoaderRoute: typeof PlanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rides/': {
      id: '/rides/'
      path: '/rides'
      fullPath: '/rides/'
      preLoaderRoute: typeof RidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rides/$slug': {
      id: '/rides/$slug'
      path: '/rides/$slug'
      fullPath: '/rides/$slug'
      preLoaderRoute: typeof RidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRouteRoute
    }
    '/shop/$category': {
      id: '/shop/$category'
      path: '/$category'
      fullPath: '/shop/$category'
      preLoaderRoute: typeof ShopCategoryRouteImport
      parentRoute: typeof ShopRouteRoute
    }
    '/stories/': {
      id: '/stories/'
      path: '/stories'
      fullPath: '/stories/'
      preLoaderRoute: typeof StoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$slug': {
      id: '/stories/$slug'
      path: '/stories/$slug'
      fullPath: '/stories/$slug'
      preLoaderRoute: typeof StoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel/': {
      id: '/travel/'
      path: '/travel'
      fullPath: '/travel/'
      preLoaderRoute: typeof TravelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel/$destination': {
      id: '/travel/$destination'
      path: '/travel/$destination'
      fullPath: '/travel/$destination'
      preLoaderRoute: typeof TravelDestinationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel/destinations': {
      id: '/travel/destinations'
      path: '/travel/destinations'
      fullPath: '/travel/destinations'
      preLoaderRoute: typeof TravelDestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/community/': {
      id: '/admin/community/'
      path: '/community'
      fullPath: '/admin/community/'
      preLoaderRoute: typeof AdminCommunityIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/community/founders': {
      id: '/admin/community/founders'
      path: '/community/founders'
      fullPath: '/admin/community/founders'
      preLoaderRoute: typeof AdminCommunityFoundersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/community/groups': {
      id: '/admin/community/groups'
      path: '/community/groups'
      fullPath: '/admin/community/groups'
      preLoaderRoute: typeof AdminCommunityGroupsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/community/riders': {
      id: '/admin/community/riders'
      path: '/community/riders'
      fullPath: '/admin/community/riders'
      preLoaderRoute: typeof AdminCommunityRidersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/community/stories': {
      id: '/admin/community/stories'
      path: '/community/stories'
      fullPath: '/admin/community/stories'
      preLoaderRoute: typeof AdminCommunityStoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/destinations/': {
      id: '/admin/destinations/'
      path: '/destinations'
      fullPath: '/admin/destinations/'
      preLoaderRoute: typeof AdminDestinationsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/destinations/$destinationId': {
      id: '/admin/destinations/$destinationId'
      path: '/destinations/$destinationId'
      fullPath: '/admin/destinations/$destinationId'
      preLoaderRoute: typeof AdminDestinationsDestinationIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/destinations/new': {
      id: '/admin/destinations/new'
      path: '/destinations/new'
      fullPath: '/admin/destinations/new'
      preLoaderRoute: typeof AdminDestinationsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products/$productId': {
      id: '/admin/products/$productId'
      path: '/products/$productId'
      fullPath: '/admin/products/$productId'
      preLoaderRoute: typeof AdminProductsProductIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/rides/': {
      id: '/admin/rides/'
      path: '/rides'
      fullPath: '/admin/rides/'
      preLoaderRoute: typeof AdminRidesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/rides/$rideId': {
      id: '/admin/rides/$rideId'
      path: '/rides/$rideId'
      fullPath: '/admin/rides/$rideId'
      preLoaderRoute: typeof AdminRidesRideIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/rides/new': {
      id: '/admin/rides/new'
      path: '/rides/new'
      fullPath: '/admin/rides/new'
      preLoaderRoute: typeof AdminRidesNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/trips/': {
      id: '/admin/trips/'
      path: '/trips'
      fullPath: '/admin/trips/'
      preLoaderRoute: typeof AdminTripsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/trips/$tripId': {
      id: '/admin/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/admin/trips/$tripId'
      preLoaderRoute: typeof AdminTripsTripIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/trips/new': {
      id: '/admin/trips/new'
      path: '/trips/new'
      fullPath: '/admin/trips/new'
      preLoaderRoute: typeof AdminTripsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/community/groups/': {
      id: '/community/groups/'
      path: '/'
      fullPath: '/community/groups/'
      preLoaderRoute: typeof CommunityGroupsIndexRouteImport
      parentRoute: typeof CommunityGroupsRoute
    }
    '/community/groups/$slug': {
      id: '/community/groups/$slug'
      path: '/$slug'
      fullPath: '/community/groups/$slug'
      preLoaderRoute: typeof CommunityGroupsSlugRouteImport
      parentRoute: typeof CommunityGroupsRoute
    }
    '/my-36-spokes/journeys/': {
      id: '/my-36-spokes/journeys/'
      path: '/journeys'
      fullPath: '/my-36-spokes/journeys/'
      preLoaderRoute: typeof My36SpokesJourneysIndexRouteImport
      parentRoute: typeof My36SpokesRouteRoute
    }
    '/my-36-spokes/journeys/$journeyId': {
      id: '/my-36-spokes/journeys/$journeyId'
      path: '/journeys/$journeyId'
      fullPath: '/my-36-spokes/journeys/$journeyId'
      preLoaderRoute: typeof My36SpokesJourneysJourneyIdRouteImport
      parentRoute: typeof My36SpokesRouteRoute
    }
    '/rides/$slug_/book': {
      id: '/rides/$slug_/book'
      path: '/rides/$slug/book'
      fullPath: '/rides/$slug/book'
      preLoaderRoute: typeof RidesSlugBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel/trips/': {
      id: '/travel/trips/'
      path: '/travel/trips'
      fullPath: '/travel/trips/'
      preLoaderRoute: typeof TravelTripsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel/trips/$slug': {
      id: '/travel/trips/$slug'
      path: '/travel/trips/$slug'
      fullPath: '/travel/trips/$slug'
      preLoaderRoute: typeof TravelTripsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminBikesRoute: typeof AdminBikesRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminHeroRoute: typeof AdminHeroRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminPathsRoute: typeof AdminPathsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminSocialRoute: typeof AdminSocialRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCommunityFoundersRoute: typeof AdminCommunityFoundersRoute
  AdminCommunityGroupsRoute: typeof AdminCommunityGroupsRoute
  AdminCommunityRidersRoute: typeof AdminCommunityRidersRoute
  AdminCommunityStoriesRoute: typeof AdminCommunityStoriesRoute
  AdminDestinationsDestinationIdRoute: typeof AdminDestinationsDestinationIdRoute
  AdminDestinationsNewRoute: typeof AdminDestinationsNewRoute
  AdminProductsProductIdRoute: typeof AdminProductsProductIdRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminRidesRideIdRoute: typeof AdminRidesRideIdRoute
  AdminRidesNewRoute: typeof AdminRidesNewRoute
  AdminTripsTripIdRoute: typeof AdminTripsTripIdRoute
  AdminTripsNewRoute: typeof AdminTripsNewRoute
  AdminCommunityIndexRoute: typeof AdminCommunityIndexRoute
  AdminDestinationsIndexRoute: typeof AdminDestinationsIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminRidesIndexRoute: typeof AdminRidesIndexRoute
  AdminTripsIndexRoute: typeof AdminTripsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminBikesRoute: AdminBikesRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminHeroRoute: AdminHeroRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminPathsRoute: AdminPathsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminSocialRoute: AdminSocialRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCommunityFoundersRoute: AdminCommunityFoundersRoute,
  AdminCommunityGroupsRoute: AdminCommunityGroupsRoute,
  AdminCommunityRidersRoute: AdminCommunityRidersRoute,
  AdminCommunityStoriesRoute: AdminCommunityStoriesRoute,
  AdminDestinationsDestinationIdRoute: AdminDestinationsDestinationIdRoute,
  AdminDestinationsNewRoute: AdminDestinationsNewRoute,
  AdminProductsProductIdRoute: AdminProductsProductIdRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminRidesRideIdRoute: AdminRidesRideIdRoute,
  AdminRidesNewRoute: AdminRidesNewRoute,
  AdminTripsTripIdRoute: AdminTripsTripIdRoute,
  AdminTripsNewRoute: AdminTripsNewRoute,
  AdminCommunityIndexRoute: AdminCommunityIndexRoute,
  AdminDestinationsIndexRoute: AdminDestinationsIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminRidesIndexRoute: AdminRidesIndexRoute,
  AdminTripsIndexRoute: AdminTripsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface My36SpokesRouteRouteChildren {
  My36SpokesCommunityRoute: typeof My36SpokesCommunityRoute
  My36SpokesGarageRoute: typeof My36SpokesGarageRoute
  My36SpokesRidesRoute: typeof My36SpokesRidesRoute
  My36SpokesShopRoute: typeof My36SpokesShopRoute
  My36SpokesTravelRoute: typeof My36SpokesTravelRoute
  My36SpokesIndexRoute: typeof My36SpokesIndexRoute
  My36SpokesJourneysJourneyIdRoute: typeof My36SpokesJourneysJourneyIdRoute
  My36SpokesJourneysIndexRoute: typeof My36SpokesJourneysIndexRoute
}

const My36SpokesRouteRouteChildren: My36SpokesRouteRouteChildren = {
  My36SpokesCommunityRoute: My36SpokesCommunityRoute,
  My36SpokesGarageRoute: My36SpokesGarageRoute,
  My36SpokesRidesRoute: My36SpokesRidesRoute,
  My36SpokesShopRoute: My36SpokesShopRoute,
  My36SpokesTravelRoute: My36SpokesTravelRoute,
  My36SpokesIndexRoute: My36SpokesIndexRoute,
  My36SpokesJourneysJourneyIdRoute: My36SpokesJourneysJourneyIdRoute,
  My36SpokesJourneysIndexRoute: My36SpokesJourneysIndexRoute,
}

const My36SpokesRouteRouteWithChildren = My36SpokesRouteRoute._addFileChildren(
  My36SpokesRouteRouteChildren,
)

interface ShopRouteRouteChildren {
  ShopCategoryRoute: typeof ShopCategoryRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteRouteChildren: ShopRouteRouteChildren = {
  ShopCategoryRoute: ShopCategoryRoute,
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteRouteWithChildren = ShopRouteRoute._addFileChildren(
  ShopRouteRouteChildren,
)

interface CommunityGroupsRouteChildren {
  CommunityGroupsSlugRoute: typeof CommunityGroupsSlugRoute
  CommunityGroupsIndexRoute: typeof CommunityGroupsIndexRoute
}

const CommunityGroupsRouteChildren: CommunityGroupsRouteChildren = {
  CommunityGroupsSlugRoute: CommunityGroupsSlugRoute,
  CommunityGroupsIndexRoute: CommunityGroupsIndexRoute,
}

const CommunityGroupsRouteWithChildren = CommunityGroupsRoute._addFileChildren(
  CommunityGroupsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  My36SpokesRouteRoute: My36SpokesRouteRouteWithChildren,
  ShopRouteRoute: ShopRouteRouteWithChildren,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  CommunityGroupsRoute: CommunityGroupsRouteWithChildren,
  CommunityRidersRoute: CommunityRidersRoute,
  GarageBikeRoute: GarageBikeRoute,
  ProductSlugRoute: ProductSlugRoute,
  RidesSlugRoute: RidesSlugRoute,
  StoriesSlugRoute: StoriesSlugRoute,
  TravelDestinationRoute: TravelDestinationRoute,
  TravelDestinationsRoute: TravelDestinationsRoute,
  AboutIndexRoute: AboutIndexRoute,
  CommunityIndexRoute: CommunityIndexRoute,
  GarageIndexRoute: GarageIndexRoute,
  PlanIndexRoute: PlanIndexRoute,
  RidesIndexRoute: RidesIndexRoute,
  StoriesIndexRoute: StoriesIndexRoute,
  TravelIndexRoute: TravelIndexRoute,
  RidesSlugBookRoute: RidesSlugBookRoute,
  TravelTripsSlugRoute: TravelTripsSlugRoute,
  TravelTripsIndexRoute: TravelTripsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
